name: Exploring Variables and Secrets

on:
    push

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx 

jobs:
  docker_build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Docker Image Build
      run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    - name: Docker Login
      run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Publish
      run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  