name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
            
        - name: Executing Shell Script
          run: ./generate-ascii.sh      

        - name: List Repo Files
          run: ls -ltra